/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_chudian_mj_bean_Match */

#ifndef _Included_org_chudian_mj_bean_Match
#define _Included_org_chudian_mj_bean_Match
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_chudian_mj_bean_Match
 * Method:    train
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT jint JNICALL Java_org_chudian_mj_bean_Match_train//Java_org_chudian_mj_bean_Match_train
  (JNIEnv * env, jclass arg, jstring trainDir, jstring feaDir, jstring indexPath);


JNIEXPORT jint JNICALL Java_org_chudian_mj_bean_Match_reTrain//Java_org_chudian_mj_bean_Match_reTrain
  (JNIEnv * env, jclass arg, jstring trainDir, jstring feaDir, jstring indexPath);

/*
 * Class:     org_chudian_mj_bean_Match
 * Method:    load
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_chudian_mj_bean_Match_load//Java_org_chudian_mj_bean_Match_load
   (JNIEnv * env, jclass arg, jstring indexPath);

/*
 * Class:     org_chudian_mj_bean_Match
 * Method:    match
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_chudian_mj_bean_Match_match//Java_org_chudian_mj_bean_Match_match
   (JNIEnv * env, jclass arg, jstring pathname, jstring feaDir, jstring trainDir);

/*
 * Class:     org_chudian_mj_bean_Match
 * Method:    matchDir
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT jint JNICALL Java_org_chudian_mj_bean_Match_matchDir//Java_org_chudian_mj_bean_Match_matchDir
  (JNIEnv * env, jclass arg, jstring matchDir, jstring feaDir, jstring trainDir);

#ifdef __cplusplus
}
#endif
#endif
